# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Scripts
        run: |
          docker build -t serverapp .
          docker tag serverapp imrankazi90/tserver
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_SECRET}}
          docker push imrankazi90/tserver
          
      
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
     - name: Pulling Dockerhub image and running on AWS EC2 server
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.ACTION_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_SECRET}}
          docker pull ${{secrets.DOCKER_USER}}/tserver
          docker stop serverc
          docker rm serverc
          docker run --name serverc -p 7000:7000 -d ${{secrets.DOCKER_USER}}/tserver
            
          
        
          
